### ISSUE TITLE
Support for Ropot?

### ISSUE THREAD

**Issue by Jujonet** [barnybug/miflora#2]
Would be nice to add support for xiaomi ropot.
According to: https://github.com/open-homeautomation/miflora/issues/110:

-------------------------------------------------Quote --------------------------------------------------------
Hi,

According to this project:

https://github.com/WeeJeWel/com.mi.flora/blob/master/drivers/ropot/device.js
https://github.com/WeeJeWel/com.mi.flora/blob/master/drivers/flora/device.js

the data is stored in almost the same way and in the same location (excluding light intensity ofc.)

Only problem is that the Ropot seems to return 24 bytes versus the Flora's 16, so the current implementation raises an exception when checking the length of _cache - line 138 in the poller - as well when unpacking the data during parsing. Trimming the cache seems to work fine, however, not sure if anything relevant is stored there.

-----------------------------------------------------------------------------------------------------------------

**Comment by barnybug** [comment]
The ropot works fine with my tool miflora. Think you've got the wrong project!
